### ISSUE TITLE
blocker!

### ISSUE THREAD

**Issue by salutuj** [rrhuffy/hybristools#1]
if (wolny_wieczor_w_piatek) {
  getBeerService().wpadaj_do_cybertapa_na_piwo_Si("2023-10-20 17:00 CET");
} else {
  getBeerService().wpadaj_do_cybertapa_na_piwo_Si("2023-10-20 17:00 CET", new WymowkaDlaZajmujacegoSlotCzasowy());
}

**Comment by rrhuffy** [comment]
if (getBeerService().isAlive("2023-10-20 17:00 CEST")) {
  getBeerService().apply(this);
}

**Comment by salutuj** [comment]
if (wolny_wieczor_w_piatek) {
getBeerService().wpadaj_na_piwo_Si("Upojeni", "2024-10-25 17:00 CET");
} else {
getBeerService().wpadaj_na_piwo_Si("Upojeni", "2023-10-25 17:00 CET", new WymowkaDlaZajmujacegoSlotCzasowy());
}
